### ISSUE TITLE
Guinea Pellets (ITEM)

### ISSUE THREAD

**Issue by LPouliot** [SomethingGeneric/GuineaBigs#7]
They can be used as a way to fertilize crops and be put in those compost bins. Also probably can be used in a furnace but it runs out very quickly 

## Tasks:
- [x] Item exists (lol)
- [x] Compost bins
- [x] Weak fuel
- [x] "Dropped" randomly by Guinea Pigs (after #10)
  - [x] Make a block variant that the boys can randomly place, which gets broken for the pellet item 
- [x] Fertilize crops (also after #10)

**Comment by SomethingGeneric** [comment]
- [ ] Item exists (lol)
- [ ] Fertilize crops
- [ ] Compost bins
- [ ] Weak fuel

**Comment by SomethingGeneric** [comment]
Fertilizer seems surprisingly complex, so that'll be after I deal with making the creatures lol

**Comment by SomethingGeneric** [comment]
Ok, fertilizer is done. Closing until we think of other things for this item.
